services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: phoenix_sync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "55555:5432"
    volumes:
      - ./postgres.conf:/etc/postgresql.conf:ro
    tmpfs:
      - /var/lib/postgresql/data
      - /tmp
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - config_file=/etc/postgresql.conf
